red-lamp/example-git-way-of-work

index.js
=> Feature 1-3

index.js
=> Please provide all feature 1-7

index.js
We are good to go, please merge
=> Test complete!!!

index.js
=> Good to go production

index.js
=> add feature8

index.js
=> add feature9

index.js
=> Merge to test

index.js
=> Test to Staging

index.js
=> Staging to Master

index.js
=> add feature 10

index.js
=> add feature11

index.js
=> Ready to deploy in test env

index.js
=> Ready for staging

index.js
=> Deploy to master

index.js
=> fix feature11

index.js
=> add feature12

index.js
P Toro please review again for feature13
=> add feature13

index.js
Reverts red-lamp/example-git-way-of-work#18
=> Revert "add feature13"

index.js
=> add feature15

index.js
=> add feature23

index.js
=> add feature24

index.js
Reverts red-lamp/example-git-way-of-work#68
=> Revert "add feature25"
